const DP = 2;
const SEP = '|';

const FLAG_INIT = '69';
const FLAG_OK = '200';
const FLAG_STOP = '201';
const FLAG_ERROR = '404';

const FLAG_UP_UNTIL_STOP = '101';
const FLAG_DOWN_UNTIL_STOP = '102';
const LASER_CALIBRATION_SEQ = '103';
const PH_CALIBRATION_SEQ = '104';
const DROP_SEQ = '105';
const LONG_DRIP_SEQ = '106';
const DEMO_SEQ = '107';
const LASER_ON_SEQ = '108';

export {
    DP, SEP,
    FLAG_INIT, FLAG_OK, FLAG_STOP, FLAG_ERROR,
    FLAG_UP_UNTIL_STOP, FLAG_DOWN_UNTIL_STOP, LASER_CALIBRATION_SEQ, PH_CALIBRATION_SEQ, DROP_SEQ, LONG_DRIP_SEQ, DEMO_SEQ, LASER_ON_SEQ
}